### ISSUE TITLE
Do we really need ConfigInterface

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/phpunit-plugin#25]
I see `interface ConfigInterface`  but that doesn't look very useful to me. It adds a layer of abstraction but I don't see the practical reason for it. 

For the purposes of writing other PHP plugins we can always use inheritance, no ? 

So 2 main questions here: 

1) Is there a practical reason for the existence of the ConfigInterface class ?
2) Will something break if we remove this class ?

**Comment by RMadjev** [comment]
IMO the purpose of it is not to cover other PHP plugins, but cases when the configuration will be provided by different way(API, DB).Overall, its good practice. 

Question 1: I would say both yes and no. If new configuration provider(different then the file system) is needed the implementation would be easier, just implement the interface. Otherwise you have to reverse eng. current Config class. On the other hand, no one asked for this feature and we could introduce it when there is such requirement.

Question 2: If you ask me, we just have to replace type hints(ConfigInterface -> Config) and the plugin will continue to work.

**Comment by atodorov** [comment]
The only possible source of configuration values for now could be environment values, which would override config file. I think we can safely remove this for now and slightly reduce code complexity. 

If we ever have the need for a config interface we can always revert the removal commit and add new code on top of it.
